### ISSUE TITLE
Processor not working on Node, but does on Bun: RdfDereferencer.dereference is undefined

### ISSUE THREAD

**Issue by smessie** [rdf-connect/ldes-client#35]
When using the ldes-client processor in an rdf-connect pipeline, it does not work when running the pipeline with Node (v20.11.1, via NPX), but it does work using Bun (v1.1.1).

After some debugging, I found out that in the case of running with Node, `RdfDereferencer.dereference` is undefined, so there might be some problems with the use of the `rdf-dereference` package.
The problem occurs here:
https://github.com/rdf-connect/ldes-client/blob/af92441b6515b28f9023dfeef45ec13614d4e672/lib/client.ts#L409

However, no exception is being reported to the console when it stops running. I figured out that it does report the stack trace when removing the extra wrapping in the `async () => {`, **what do we need this extra wrapping for?**
https://github.com/rdf-connect/ldes-client/blob/af92441b6515b28f9023dfeef45ec13614d4e672/lib/client.ts#L471

So after running the pipeline again without the extra `async () => {` wrap, we get the following stack trace:
```
Error: TypeError: dereferencer.dereference is not a function
    at fetchPage (file:///Users/ieben/Documents/UGent/PhD/c-knows/projects.nosync/ldes-client/dist/lib/client.js:230:37)
    at Client.init (file:///Users/ieben/Documents/UGent/PhD/c-knows/projects.nosync/ldes-client/dist/lib/client.js:134:28)
    at Object.start (file:///Users/ieben/Documents/UGent/PhD/c-knows/projects.nosync/ldes-client/dist/lib/client.js:199:28)
    at setupReadableStreamDefaultController (node:internal/webstreams/readablestream:2437:23)
    at setupReadableStreamDefaultControllerFromSource (node:internal/webstreams/readablestream:2470:3)
    at new ReadableStream (node:internal/webstreams/readablestream:290:7)
    at Client.stream (file:///Users/ieben/Documents/UGent/PhD/c-knows/projects.nosync/ldes-client/dist/lib/client.js:225:21)
    at Module.processor (file:///Users/ieben/Documents/UGent/PhD/c-knows/projects.nosync/ldes-client/dist/lib/client.js:263:27)
    at jsRunner (file:///Users/ieben/Documents/UGent/PhD/c-knows/projects.nosync/DCAT-AP-Feeds/node_modules/@rdfc/js-runner/bin/bundle.mjs:32882:45)
TypeError: dereferencer.dereference is not a function
    at fetchPage (file:///Users/ieben/Documents/UGent/PhD/c-knows/projects.nosync/ldes-client/dist/lib/client.js:230:37)
    at Client.init (file:///Users/ieben/Documents/UGent/PhD/c-knows/projects.nosync/ldes-client/dist/lib/client.js:134:28)
    at Object.start (file:///Users/ieben/Documents/UGent/PhD/c-knows/projects.nosync/ldes-client/dist/lib/client.js:199:28)
    at setupReadableStreamDefaultController (node:internal/webstreams/readablestream:2437:23)
    at setupReadableStreamDefaultControllerFromSource (node:internal/webstreams/readablestream:2470:3)
    at new ReadableStream (node:internal/webstreams/readablestream:290:7)
    at Client.stream (file:///Users/ieben/Documents/UGent/PhD/c-knows/projects.nosync/ldes-client/dist/lib/client.js:225:21)
    at Module.processor (file:///Users/ieben/Documents/UGent/PhD/c-knows/projects.nosync/ldes-client/dist/lib/client.js:263:27)
    at jsRunner (file:///Users/ieben/Documents/UGent/PhD/c-knows/projects.nosync/DCAT-AP-Feeds/node_modules/@rdfc/js-runner/bin/bundle.mjs:32882:45)
```

If I now add an extra `console.log("dereferencer", dereferencer);` just before it will be used, we can notice a difference between running with Node vs Bun.
While running with Node:
```
dereferencer {
  RdfDereferencer: [Getter],
  RdfDereferencerBase: [Getter],
  default: RdfDereferencer {
    mediatorDereferenceRdf: MediatorRace {
      name: 'urn:comunica:default:dereference-rdf/mediators#main',
      bus: [Bus]
    }
  }
}
```

While running with Bun:
```
dereferencer RdfDereferencer {
  mediatorDereferenceRdf: MediatorRace {
    name: "urn:comunica:default:dereference-rdf/mediators#main",
    bus: Bus {
      actors: [
        ActorDereferenceRdfParse {
          beforeActors: [],
          mediatorDereference: MediatorRace {
            name: "urn:comunica:default:dereference/mediators#main",
            bus: Bus {
              actors: [
                ActorDereferenceFile {
                  beforeActors: [],
                  name: "urn:comunica:default:dereference/actors#file",
                  bus: [Circular],
                  test: [Function: test],
                  run: [Function: run],
                  handleDereferenceErrors: [Function: handleDereferenceErrors],
                  dereferenceErrorHandler: [Function: dereferenceErrorHandler],
                  runObservable: [Function: runObservable],
                  initialize: [Function: initialize],
                  deinitialize: [Function: deinitialize],
                  getDefaultLogData: [Function: getDefaultLogData],
                  logTrace: [Function: logTrace],
                  logDebug: [Function: logDebug],
                  logInfo: [Function: logInfo],
                  logWarn: [Function: logWarn],
                  logError: [Function: logError],
                  logFatal: [Function: logFatal],
                }, ActorDereferenceHttp {
                  beforeActors: [
                    [Object ...]
                  ],
                  mediatorHttp: [Object ...],
                  maxAcceptHeaderLength: 1024,
                  maxAcceptHeaderLengthBrowser: 128,
                  name: "urn:comunica:default:dereference/actors#http",
                  bus: [Circular],
                  getMaxAcceptHeaderLength: [Function: getMaxAcceptHeaderLength],
                  test: [Function: test],
                  run: [Function: run],
                  handleDereferenceErrors: [Function: handleDereferenceErrors],
                  dereferenceErrorHandler: [Function: dereferenceErrorHandler],
                  runObservable: [Function: runObservable],
                  initialize: [Function: initialize],
                  deinitialize: [Function: deinitialize],
                  getDefaultLogData: [Function: getDefaultLogData],
                  logTrace: [Function: logTrace],
                  logDebug: [Function: logDebug],
                  logInfo: [Function: logInfo],
                  logWarn: [Function: logWarn],
                  logError: [Function: logError],
                  logFatal: [Function: logFatal],
                }, ActorDereferenceFallback {
                  beforeActors: [],
                  name: "urn:comunica:default:dereference/actors#fallback",
                  bus: [Circular],
                  test: [Function: test],
                  run: [Function: run],
                  handleDereferenceErrors: [Function: handleDereferenceErrors],
                  dereferenceErrorHandler: [Function: dereferenceErrorHandler],
                  runObservable: [Function: runObservable],
                  initialize: [Function: initialize],
                  deinitialize: [Function: deinitialize],
                  getDefaultLogData: [Function: getDefaultLogData],
                  logTrace: [Function: logTrace],
                  logDebug: [Function: logDebug],
                  logInfo: [Function: logInfo],
                  logWarn: [Function: logWarn],
                  logError: [Function: logError],
                  logFatal: [Function: logFatal],
                }
              ],
              observers: [],
              dependencyLinks: Map(1) {
                ActorDereferenceFallback {
                  beforeActors: [],
                  name: "urn:comunica:default:dereference/actors#fallback",
                  bus: [Circular],
                  test: [Function: test],
                  run: [Function: run],
                  handleDereferenceErrors: [Function: handleDereferenceErrors],
                  dereferenceErrorHandler: [Function: dereferenceErrorHandler],
                  runObservable: [Function: runObservable],
                  initialize: [Function: initialize],
                  deinitialize: [Function: deinitialize],
                  getDefaultLogData: [Function: getDefaultLogData],
                  logTrace: [Function: logTrace],
                  logDebug: [Function: logDebug],
                  logInfo: [Function: logInfo],
                  logWarn: [Function: logWarn],
                  logError: [Function: logError],
                  logFatal: [Function: logFatal],
                }: [
                  [Object ...]
                ],
              },
              name: "https://linkedsoftwaredependencies.org/bundles/npm/@comunica/bus-dereference/^2.0.0/components/ActorDereference.jsonld#ActorDereference_default_bus",
              subscribe: [Function: subscribe],
              subscribeObserver: [Function: subscribeObserver],
              unsubscribe: [Function: unsubscribe],
              unsubscribeObserver: [Function: unsubscribeObserver],
              publish: [Function: publish],
              onRun: [Function: onRun],
              addDependencies: [Function: addDependencies],
              reorderForDependencies: [Function: reorderForDependencies],
            },
            mediateWith: [Function: mediateWith],
            publish: [Function: publish],
            mediateActor: [Function: mediateActor],
            mediate: [Function: mediate],
          },
          mediatorParse: MediatorRace {
            name: "urn:comunica:default:rdf-parse/mediators#parse",
            bus: Bus {
              actors: [
                ActorRdfParseN3 {
                  beforeActors: [],
                  mediaTypePriorities: [Object ...],
                  mediaTypeFormats: [Object ...],
                  priorityScale: 1,
                  name: "urn:comunica:default:rdf-parse/actors#n3",
                  bus: [Circular],
                  runHandle: [Function: runHandle],
                  testHandleChecked: [Function: testHandleChecked],
                  testHandle: [Function: testHandle],
                  testMediaType: [Function: testMediaType],
                  getMediaTypes: [Function: getMediaTypes],
                  testMediaTypeFormats: [Function: testMediaTypeFormats],
                  getMediaTypeFormats: [Function: getMediaTypeFormats],
                  run: [Function: run],
                  test: [Function: test],
                  runObservable: [Function: runObservable],
                  initialize: [Function: initialize],
                  deinitialize: [Function: deinitialize],
                  getDefaultLogData: [Function: getDefaultLogData],
                  logTrace: [Function: logTrace],
                  logDebug: [Function: logDebug],
                  logInfo: [Function: logInfo],
                  logWarn: [Function: logWarn],
                  logError: [Function: logError],
                  logFatal: [Function: logFatal],
                }, ActorRdfParseRdfXml {
                  beforeActors: [],
                  mediaTypePriorities: [Object ...],
                  mediaTypeFormats: [Object ...],
                  priorityScale: 0.5,
                  name: "urn:comunica:default:rdf-parse/actors#rdfxml",
                  bus: [Circular],
                  runHandle: [Function: runHandle],
                  testHandleChecked: [Function: testHandleChecked],
                  testHandle: [Function: testHandle],
                  testMediaType: [Function: testMediaType],
                  getMediaTypes: [Function: getMediaTypes],
                  testMediaTypeFormats: [Function: testMediaTypeFormats],
                  getMediaTypeFormats: [Function: getMediaTypeFormats],
                  run: [Function: run],
                  test: [Function: test],
                  runObservable: [Function: runObservable],
                  initialize: [Function: initialize],
                  deinitialize: [Function: deinitialize],
                  getDefaultLogData: [Function: getDefaultLogData],
                  logTrace: [Function: logTrace],
                  logDebug: [Function: logDebug],
                  logInfo: [Function: logInfo],
                  logWarn: [Function: logWarn],
                  logError: [Function: logError],
                  logFatal: [Function: logFatal],
                }, ActorRdfParseXmlRdfa {
                  beforeActors: [],
                  mediaTypePriorities: [Object ...],
                  mediaTypeFormats: [Object ...],
                  priorityScale: 0.3,
                  name: "urn:comunica:default:rdf-parse/actors#xmlrdfa",
                  bus: [Circular],
                  runHandle: [Function: runHandle],
                  testHandleChecked: [Function: testHandleChecked],
                  testHandle: [Function: testHandle],
                  testMediaType: [Function: testMediaType],
                  getMediaTypes: [Function: getMediaTypes],
                  testMediaTypeFormats: [Function: testMediaTypeFormats],
                  getMediaTypeFormats: [Function: getMediaTypeFormats],
                  run: [Function: run],
                  test: [Function: test],
                  runObservable: [Function: runObservable],
                  initialize: [Function: initialize],
                  deinitialize: [Function: deinitialize],
                  getDefaultLogData: [Function: getDefaultLogData],
                  logTrace: [Function: logTrace],
                  logDebug: [Function: logDebug],
                  logInfo: [Function: logInfo],
                  logWarn: [Function: logWarn],
                  logError: [Function: logError],
                  logFatal: [Function: logFatal],
                }, ActorRdfParseShaclc {
                  beforeActors: [],
                  mediaTypePriorities: [Object ...],
                  mediaTypeFormats: [Object ...],
                  priorityScale: 0.1,
                  name: "urn:comunica:default:rdf-parse/actors#shaclc",
                  bus: [Circular],
                  runHandle: [Function: runHandle],
                  testHandleChecked: [Function: testHandleChecked],
                  testHandle: [Function: testHandle],
                  testMediaType: [Function: testMediaType],
                  getMediaTypes: [Function: getMediaTypes],
                  testMediaTypeFormats: [Function: testMediaTypeFormats],
                  getMediaTypeFormats: [Function: getMediaTypeFormats],
                  run: [Function: run],
                  test: [Function: test],
                  runObservable: [Function: runObservable],
                  initialize: [Function: initialize],
                  deinitialize: [Function: deinitialize],
                  getDefaultLogData: [Function: getDefaultLogData],
                  logTrace: [Function: logTrace],
                  logDebug: [Function: logDebug],
                  logInfo: [Function: logInfo],
                  logWarn: [Function: logWarn],
                  logError: [Function: logError],
                  logFatal: [Function: logFatal],
                }, ActorRdfParseHtml {
                  beforeActors: [],
                  busRdfParseHtml: [Object ...],
                  mediaTypePriorities: [Object ...],
                  mediaTypeFormats: [Object ...],
                  priorityScale: 0.2,
                  name: "urn:comunica:default:rdf-parse/actors#html",
                  bus: [Circular],
                  runHandle: [Function: runHandle],
                  testHandleChecked: [Function: testHandleChecked],
                  testHandle: [Function: testHandle],
                  testMediaType: [Function: testMediaType],
                  getMediaTypes: [Function: getMediaTypes],
                  testMediaTypeFormats: [Function: testMediaTypeFormats],
                  getMediaTypeFormats: [Function: getMediaTypeFormats],
                  run: [Function: run],
                  test: [Function: test],
                  runObservable: [Function: runObservable],
                  initialize: [Function: initialize],
                  deinitialize: [Function: deinitialize],
                  getDefaultLogData: [Function: getDefaultLogData],
                  logTrace: [Function: logTrace],
                  logDebug: [Function: logDebug],
                  logInfo: [Function: logInfo],
                  logWarn: [Function: logWarn],
                  logError: [Function: logError],
                  logFatal: [Function: logFatal],
                }, ActorRdfParseJsonLd {
                  beforeActors: [],
                  mediatorHttp: [Object ...],
                  mediaTypePriorities: [Object ...],
                  mediaTypeFormats: [Object ...],
                  priorityScale: 0.9,
                  name: "urn:comunica:default:rdf-parse/actors#jsonld",
                  bus: [Circular],
                  testHandle: [Function: testHandle],
                  runHandle: [Function: runHandle],
                  testHandleChecked: [Function: testHandleChecked],
                  testMediaType: [Function: testMediaType],
                  getMediaTypes: [Function: getMediaTypes],
                  testMediaTypeFormats: [Function: testMediaTypeFormats],
                  getMediaTypeFormats: [Function: getMediaTypeFormats],
                  run: [Function: run],
                  test: [Function: test],
                  runObservable: [Function: runObservable],
                  initialize: [Function: initialize],
                  deinitialize: [Function: deinitialize],
                  getDefaultLogData: [Function: getDefaultLogData],
                  logTrace: [Function: logTrace],
                  logDebug: [Function: logDebug],
                  logInfo: [Function: logInfo],
                  logWarn: [Function: logWarn],
                  logError: [Function: logError],
                  logFatal: [Function: logFatal],
                }
              ],
              observers: [],
              dependencyLinks: Map {},
              name: "https://linkedsoftwaredependencies.org/bundles/npm/@comunica/bus-rdf-parse/^2.0.0/components/ActorRdfParse.jsonld#ActorRdfParse_default_bus",
              subscribe: [Function: subscribe],
              subscribeObserver: [Function: subscribeObserver],
              unsubscribe: [Function: unsubscribe],
              unsubscribeObserver: [Function: unsubscribeObserver],
              publish: [Function: publish],
              onRun: [Function: onRun],
              addDependencies: [Function: addDependencies],
              reorderForDependencies: [Function: reorderForDependencies],
            },
            mediateWith: [Function: mediateWith],
            publish: [Function: publish],
            mediateActor: [Function: mediateActor],
            mediate: [Function: mediate],
          },
          mediatorParseMediatypes: MediatorCombineUnion {
            field: "mediaTypes",
            name: "urn:comunica:default:rdf-parse/mediators#mediaType",
            bus: Bus {
              actors: [
                ActorRdfParseN3 {
                  beforeActors: [],
                  mediaTypePriorities: [Object ...],
                  mediaTypeFormats: [Object ...],
                  priorityScale: 1,
                  name: "urn:comunica:default:rdf-parse/actors#n3",
                  bus: [Circular],
                  runHandle: [Function: runHandle],
                  testHandleChecked: [Function: testHandleChecked],
                  testHandle: [Function: testHandle],
                  testMediaType: [Function: testMediaType],
                  getMediaTypes: [Function: getMediaTypes],
                  testMediaTypeFormats: [Function: testMediaTypeFormats],
                  getMediaTypeFormats: [Function: getMediaTypeFormats],
                  run: [Function: run],
                  test: [Function: test],
                  runObservable: [Function: runObservable],
                  initialize: [Function: initialize],
                  deinitialize: [Function: deinitialize],
                  getDefaultLogData: [Function: getDefaultLogData],
                  logTrace: [Function: logTrace],
                  logDebug: [Function: logDebug],
                  logInfo: [Function: logInfo],
                  logWarn: [Function: logWarn],
                  logError: [Function: logError],
                  logFatal: [Function: logFatal],
                }, ActorRdfParseRdfXml {
                  beforeActors: [],
                  mediaTypePriorities: [Object ...],
                  mediaTypeFormats: [Object ...],
                  priorityScale: 0.5,
                  name: "urn:comunica:default:rdf-parse/actors#rdfxml",
                  bus: [Circular],
                  runHandle: [Function: runHandle],
                  testHandleChecked: [Function: testHandleChecked],
                  testHandle: [Function: testHandle],
                  testMediaType: [Function: testMediaType],
                  getMediaTypes: [Function: getMediaTypes],
                  testMediaTypeFormats: [Function: testMediaTypeFormats],
                  getMediaTypeFormats: [Function: getMediaTypeFormats],
                  run: [Function: run],
                  test: [Function: test],
                  runObservable: [Function: runObservable],
                  initialize: [Function: initialize],
                  deinitialize: [Function: deinitialize],
                  getDefaultLogData: [Function: getDefaultLogData],
                  logTrace: [Function: logTrace],
                  logDebug: [Function: logDebug],
                  logInfo: [Function: logInfo],
                  logWarn: [Function: logWarn],
                  logError: [Function: logError],
                  logFatal: [Function: logFatal],
                }, ActorRdfParseXmlRdfa {
                  beforeActors: [],
                  mediaTypePriorities: [Object ...],
                  mediaTypeFormats: [Object ...],
                  priorityScale: 0.3,
                  name: "urn:comunica:default:rdf-parse/actors#xmlrdfa",
                  bus: [Circular],
                  runHandle: [Function: runHandle],
                  testHandleChecked: [Function: testHandleChecked],
                  testHandle: [Function: testHandle],
                  testMediaType: [Function: testMediaType],
                  getMediaTypes: [Function: getMediaTypes],
                  testMediaTypeFormats: [Function: testMediaTypeFormats],
                  getMediaTypeFormats: [Function: getMediaTypeFormats],
                  run: [Function: run],
                  test: [Function: test],
                  runObservable: [Function: runObservable],
                  initialize: [Function: initialize],
                  deinitialize: [Function: deinitialize],
                  getDefaultLogData: [Function: getDefaultLogData],
                  logTrace: [Function: logTrace],
                  logDebug: [Function: logDebug],
                  logInfo: [Function: logInfo],
                  logWarn: [Function: logWarn],
                  logError: [Function: logError],
                  logFatal: [Function: logFatal],
                }, ActorRdfParseShaclc {
                  beforeActors: [],
                  mediaTypePriorities: [Object ...],
                  mediaTypeFormats: [Object ...],
                  priorityScale: 0.1,
                  name: "urn:comunica:default:rdf-parse/actors#shaclc",
                  bus: [Circular],
                  runHandle: [Function: runHandle],
                  testHandleChecked: [Function: testHandleChecked],
                  testHandle: [Function: testHandle],
                  testMediaType: [Function: testMediaType],
                  getMediaTypes: [Function: getMediaTypes],
                  testMediaTypeFormats: [Function: testMediaTypeFormats],
                  getMediaTypeFormats: [Function: getMediaTypeFormats],
                  run: [Function: run],
                  test: [Function: test],
                  runObservable: [Function: runObservable],
                  initialize: [Function: initialize],
                  deinitialize: [Function: deinitialize],
                  getDefaultLogData: [Function: getDefaultLogData],
                  logTrace: [Function: logTrace],
                  logDebug: [Function: logDebug],
                  logInfo: [Function: logInfo],
                  logWarn: [Function: logWarn],
                  logError: [Function: logError],
                  logFatal: [Function: logFatal],
                }, ActorRdfParseHtml {
                  beforeActors: [],
                  busRdfParseHtml: [Object ...],
                  mediaTypePriorities: [Object ...],
                  mediaTypeFormats: [Object ...],
                  priorityScale: 0.2,
                  name: "urn:comunica:default:rdf-parse/actors#html",
                  bus: [Circular],
                  runHandle: [Function: runHandle],
                  testHandleChecked: [Function: testHandleChecked],
                  testHandle: [Function: testHandle],
                  testMediaType: [Function: testMediaType],
                  getMediaTypes: [Function: getMediaTypes],
                  testMediaTypeFormats: [Function: testMediaTypeFormats],
                  getMediaTypeFormats: [Function: getMediaTypeFormats],
                  run: [Function: run],
                  test: [Function: test],
                  runObservable: [Function: runObservable],
                  initialize: [Function: initialize],
                  deinitialize: [Function: deinitialize],
                  getDefaultLogData: [Function: getDefaultLogData],
                  logTrace: [Function: logTrace],
                  logDebug: [Function: logDebug],
                  logInfo: [Function: logInfo],
                  logWarn: [Function: logWarn],
                  logError: [Function: logError],
                  logFatal: [Function: logFatal],
                }, ActorRdfParseJsonLd {
                  beforeActors: [],
                  mediatorHttp: [Object ...],
                  mediaTypePriorities: [Object ...],
                  mediaTypeFormats: [Object ...],
                  priorityScale: 0.9,
                  name: "urn:comunica:default:rdf-parse/actors#jsonld",
                  bus: [Circular],
                  testHandle: [Function: testHandle],
                  runHandle: [Function: runHandle],
                  testHandleChecked: [Function: testHandleChecked],
                  testMediaType: [Function: testMediaType],
                  getMediaTypes: [Function: getMediaTypes],
                  testMediaTypeFormats: [Function: testMediaTypeFormats],
                  getMediaTypeFormats: [Function: getMediaTypeFormats],
                  run: [Function: run],
                  test: [Function: test],
                  runObservable: [Function: runObservable],
                  initialize: [Function: initialize],
                  deinitialize: [Function: deinitialize],
                  getDefaultLogData: [Function: getDefaultLogData],
                  logTrace: [Function: logTrace],
                  logDebug: [Function: logDebug],
                  logInfo: [Function: logInfo],
                  logWarn: [Function: logWarn],
                  logError: [Function: logError],
                  logFatal: [Function: logFatal],
                }
              ],
              observers: [],
              dependencyLinks: Map {},
              name: "https://linkedsoftwaredependencies.org/bundles/npm/@comunica/bus-rdf-parse/^2.0.0/components/ActorRdfParse.jsonld#ActorRdfParse_default_bus",
              subscribe: [Function: subscribe],
              subscribeObserver: [Function: subscribeObserver],
              unsubscribe: [Function: unsubscribe],
              unsubscribeObserver: [Function: unsubscribeObserver],
              publish: [Function: publish],
              onRun: [Function: onRun],
              addDependencies: [Function: addDependencies],
              reorderForDependencies: [Function: reorderForDependencies],
            },
            combiner: [Function],
            mediate: [Function: mediate],
            mediateWith: [Function: mediateWith],
            createCombiner: [Function: createCombiner],
            publish: [Function: publish],
            mediateActor: [Function: mediateActor],
          },
          mediaMappings: {
            htm: "text/html",
            html: "text/html",
            json: "application/json",
            jsonld: "application/ld+json",
            n3: "text/n3",
            nq: "application/n-quads",
            nquads: "application/n-quads",
            nt: "application/n-triples",
            ntriples: "application/n-triples",
            owl: "application/rdf+xml",
            rdf: "application/rdf+xml",
            rdfxml: "application/rdf+xml",
            shaclc: "text/shaclc",
            shaclce: "text/shaclc-ext",
            shc: "text/shaclc",
            shce: "text/shaclc-ext",
            svg: "image/svg+xml",
            svgz: "image/svg+xml",
            trig: "application/trig",
            ttl: "text/turtle",
            turtle: "text/turtle",
            xht: "application/xhtml+xml",
            xhtml: "application/xhtml+xml",
            xml: "application/xml",
          },
          name: "urn:comunica:default:dereference-rdf/actors#parse",
          bus: [Circular],
          getMetadata: [Function: getMetadata],
          test: [Function: test],
          handleDereferenceStreamErrors: [Function: handleDereferenceStreamErrors],
          run: [Function: run],
          dereferenceErrorHandler: [Function: dereferenceErrorHandler],
        }
      ],
      observers: [],
      dependencyLinks: Map {},
      name: "https://linkedsoftwaredependencies.org/bundles/npm/@comunica/bus-dereference-rdf/^2.0.0/components/ActorDereferenceRdf.jsonld#ActorDereferenceRdf_default_bus",
      subscribe: [Function: subscribe],
      subscribeObserver: [Function: subscribeObserver],
      unsubscribe: [Function: unsubscribe],
      unsubscribeObserver: [Function: unsubscribeObserver],
      publish: [Function: publish],
      onRun: [Function: onRun],
      addDependencies: [Function: addDependencies],
      reorderForDependencies: [Function: reorderForDependencies],
    },
    mediateWith: [Function: mediateWith],
    publish: [Function: publish],
    mediateActor: [Function: mediateActor],
    mediate: [Function: mediate],
  },
  dereference: [Function: dereference],
}
```

**Comment by smessie** [comment]
Most likely related to https://github.com/rubensworks/rdf-parse.js/issues/57 (but the same issue in rdf-dereference).

**Comment by smessie** [comment]
Fixed in https://github.com/rdf-connect/ldes-client/commit/792a6e9a950a3d882b407cbf29d1db4a7e48b980 and published as `0.0.10-alpha-8`
